formbricks/oss.gg

- app/[githubLogin]/page.tsx
- lib/github/service.ts
feat: move github calls to service
> feat: move github calls to service

- .env.example
- app/(dashboard)/client-page.tsx
- app/(dashboard)/issues/actions.ts
- app/(dashboard)/layout.tsx
- app/(marketing)/page.tsx
- env.mjs
- lib/auth.ts
- lib/constants.ts
- lib/github/index.ts
- lib/github/service.ts
- lib/github/services/user.ts
- lib/github/utils.ts
- lib/githubUser/service.ts
New environment variables:
```
GITHUB_APP_ID: z.string().min(1),
GITHUB_APP_CLIENT_ID: z.string().min(1),
GITHUB_APP_CLIENT_SECRET: z.string().min(1),
GITHUB_APP_WEBHOOK_SECRET: z.string().min(1).optional(),
GITHUB_APP_PRIVATE_KEY: z.string().min(1).optional(),
GITHUB_APP_INSTALLATION_URL: z.string().min(1),
GITHUB_APP_ACCESS_TOKEN: z.string().min(1),
```
> chore: rewrite env vars cleanly

- app/(dashboard)/enroll/[repositoryId]/actions.ts
- app/(dashboard)/enroll/[repositoryId]/enrollmentStatusBar.tsx
- lib/enrollment/service.ts
> debug: enrollment action

- lib/enrollment/service.ts
> debug: restructure logs

- app/(dashboard)/enroll/[repositoryId]/actions.ts
- app/(dashboard)/enroll/[repositoryId]/enrollmentStatusBar.tsx
- lib/enrollment/service.ts
> debug: remove console logs

- app/(dashboard)/enroll/[repositoryId]/page.tsx
- components/ui/tabs.tsx
- package.json
- pnpm-lock.yaml
1. Add reusable tabs in `components/ui` 
2. Use the tabs in the `enroll-project` page
https://github.com/formbricks/oss.gg/issues/33
Loom Video: https://www.loom.com/share/1c42ed1b74e0486e81e1ce6bebe467bd?sid=414e5b65-e7aa-4295-895e-d4ebc65b9e06
- Test A
- Test B
> feat(ui): Add reusable tabs & add them in the enroll project page

- app/(dashboard)/issues/page.tsx
- lib/github/service.ts
- lib/repository/service.ts
- Only show the configured repositories in the /enroll page
- Show Issues based on what repos a user has enrolled to (& their image avatars as well based on it)
> feat: enrolled issues of dynamic enrolled repos + their images

- app/(marketing)/founding-team/page.tsx
- app/(marketing)/layout.tsx
- app/(marketing)/page.tsx
- next.config.mjs
> add founding member page

- app/(marketing)/founding-team/page.tsx
added "manish" to founding team page
- Test A
- Test B
> feat: added "manish" to founding team page

- app/(marketing)/founding-team/page.tsx
> fix: Update role

- z_pm-work/contribution-log.txt
Closes #36
Link to Bounties Concept Added. [Click to read](https://blessingojediran.notion.site/Bounty-System-A-Unified-Concept-98036ce70e954d78a76f2afb76fec88e?pvs=4) 
Fixes #36
> docs: Added Unified Bounties Concept

- components/ui/githubIssue.tsx
- lib/github/service.ts
Fixes https://github.com/formbricks/oss.gg/issues/58
- Test A
- Test B
> feat: Add repository name to meta data on open issue page

- app/(dashboard)/dashboard/page.tsx
- components/header.tsx
- components/ui/pointsCard.tsx
- components/user-account-nav.tsx
- lib/utils/textformat.ts
Adds Score Card
Fixes #54
Click on avatar on top left and go to dashboard ,you will find your rank and points in the repo you are enrolled in.
> feat: Add Score Card

- lib/constants.ts
Reduce cache time to 1 hour 
Fixes #57 
- Test A
- Test B
> fix: make github revalidation cache time to 1 hour

- z_community-work/contribution-log.txt
1. help identify members with specific roles or expertise within the community. "Developer", "Designer", "PMs", to showcase members' skills or areas of expertise
2. To organize members within the oss server based on their roles, responsibilities, or permissions.This makes it easier to manage and interact with different groups of users.
3. Channels for regular updates, Questions and Answers for members to always find and recieve help from other members
4. channels for job posting and monthly meet up
Fixes #44
> docs(community): add discord role contribution to community-work.txt

- app/(dashboard)/issues/page.tsx
- lib/github/services/repo.ts
1. Add tabs in open issues to segregate issues based on the selected repo
Fixes https://github.com/formbricks/oss.gg/issues/68
https://github.com/formbricks/oss.gg/assets/66999381/c4c086d2-0a4f-4273-8f37-7fefa8ad7856
- Test A
- Test B
> feat: add tabs to open issues

- app/(dashboard)/repo-settings/[repositoryId]/players/page.tsx
- lib/repository/service.ts
Fixes #77 
go to /repo-settings/{id}/players
> fix: Replace Player List Item with Leaderboard List Item

- app/(dashboard)/enroll/[repositoryId]/layout.tsx
fixes #55 
more details of dynamic metadata here:https://nextjs.org/docs/app/building-your-application/optimizing/metadata#dynamic-metadata
[Screencast from 04-05-24 06:07:31 PM IST.webm](https://github.com/formbricks/oss.gg/assets/114493480/ca4c49cb-e3b8-4324-b0ee-f3cefe0c39ac)
go to a repo detail page
> fix: Fix hard coded page title 

- app/layout.tsx
- next.config.mjs
1. Adds `metadataBase` to resolve the console errors
2. Removes `appDir` from next config
- Test A
- Test B
> fix: resolve console warnings

- components/ui/levelDetailCard.tsx
fix: upto two decimal points in progress,showing completed when points equal threshold
- Test A
- Test B
> fix: upto two decimal points in progress,showing completed when points equal threshold

- app/[githubLogin]/page.tsx
- lib/github/service.ts
It fixes the incorrect pulling of user's contributions from their enrolled repositories. Instead of it pulling from the list of user enrolled repos, it was hardcoded to pull from `formbricks/formbricks`.
Fixes #90
> fix: profile display contributions

- src/trigger/issueReminder.ts
Fixes trigger timing
- Test A
- Test B
> fix: trigger timing

- middleware.ts
> fix: build error

- lib/github/service.ts
> fix: caching from getAllOssGgIssuesOfRepos

- lib/github/service.ts
> Revert "fix: caching"

- README.md
> feat: Revert "fix: update README.md"

- lib/github/hooks/issue.ts
- lib/githubUser/service.ts
> fix: remove blocking discord message

- app/(hacktoberfest)/oss-issues/page.tsx
> fix: update ossissue page

- lib/auth.ts
creates account for the user without account
- Test A
- Test B
> fix: creates account for the user without account

- lib/constants.ts
- lib/github/hooks/issue.ts
- lib/points/service.ts
1) I fixed the leadboard points 
2) Improved the comments assigning 
[screen-capture (24).webm](https://github.com/user-attachments/assets/ecd22e02-c10d-44ab-ba9f-265e44adb876)
> fix: fixed leaderboard and comments 

- app/(hacktoberfest)/page.tsx
It replaces the wrong URL of iPhone-16 with the correct URL on the home page. This PR fixes the bug [#127](https://github.com/formbricks/oss.gg/issues/127)
Fixes #127
Visit https://oss.gg/
Explad Prizes section
Click [iPhone 16 with 512GB](https://www.apple.com/iphone-16/)
You will be redirected to the iPhone-16 landing page.
> fix: Replaced iPhone-16 URL with correct URL

- app/(hacktoberfest)/leaderboard/page.tsx
ISR docs: https://nextjs.org/docs/canary/app/building-your-application/data-fetching/incremental-static-regeneration
> fix: Add ISR for leaderboard page
